### ISSUE TITLE
Install plugin xml

### ISSUE THREAD

**Issue by stonier** [ros/nodelet_core#1]
Groovy complains about the missing plugin file (nodelet_topic_tools/test/test_nodelets.xml). It needs to either get installed (aka the image pipeline plugins) or not alert the system that there is a plugin.

How does it even alert the system that there's a plugin without the plugin file?

I'll copy some more detail re the error here after reproducing again tomorrow.

**Comment by dirk-thomas** [comment]
Please explain when this happens for you. That plugin is for testing only and is neither exported in the package.xml file nor installed intentionally.

**Comment by stonier** [comment]
Sorry, I meant to get back to this, but was updating with mars on what was the same problem elsewhere. All the plugins/nodelets were failing. Most of these are fixed now, but I'll check on Monday to see if the problem still exists. It was occurrung when trying to run openni_camera/driverNodelet.

**Comment by tfoote** [comment]
Is this possibly an issue when installing from source as the package will
be there, but the xml won't be installed?

On Sat, Nov 10, 2012 at 8:28 PM, Daniel Stonier notifications@github.comwrote:

> Sorry, I meant to get back to this, but was updating with mars on what was
> the same problem elsewhere. All the plugins/nodelets were failing. Most of
> these are fixed now, but I'll check on Monday to see if the problem still
> exists. It was occurrung when trying to run openni_camera/driverNodelet.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/nodelet_core/issues/1#issuecomment-10263112.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by stonier** [comment]
Can't reproduce this. It was failing for us when loading up openni_camera/driverNodelet, but that is working now. 

And to answer your question, we were not using source.

I'll close it for now and reopen it if I come across the problem again.
