### ISSUE TITLE
nodelet increases CLOSE_WAIT of rosmaster

### ISSUE THREAD

**Issue by garaemon** [ros/nodelet_core#10]
I'm using groovy's nodelet and I found that nodelet increases CLOSE_WAIT of rosmaster.

You can simply verify that problem by launching nodelet_tutorial_math.

``` sh
$ lsof -nl | grep rosmaster | grep -c CLOSE_WAIT
=> 0
$ roslaunch nodelet_tutorial_math plus.launch
Ctrl-C
$ lsof -nl | grep rosmaster | grep -c CLOSE_WAIT
=> 4
```

It might be an issue of roscpp.

**Comment by tfoote** [comment]
Thanks for the ticket. Refiled here: https://github.com/ros/ros_comm/issues/325
