### ISSUE TITLE
Update available class list, if class is not found

### ISSUE THREAD

**Issue by bit-pirate** [ros/nodelet_core#17]
pluginlib already contains a function to update the internally stored list of available plugins/classes, `refreshDeclaredClasses()` (http://docs.ros.org/hydro/api/pluginlib/html/class__loader__imp_8h_source.html#l00619).

I suggest to make use of this function when trying to load a nodelet and the requested plugin/class couldn't be found.

**Comment by bit-pirate** [comment]
This is relevant for https://github.com/robotics-in-concert/rocon_app_platform/issues/211

**Comment by dirk-thomas** [comment]
@esteve Has this been addressed with #20?

**Comment by esteve** [comment]
@dirk-thomas Yes, closing now.
