### ISSUE TITLE
documentation request: callbacks, queues and threading

### ISSUE THREAD

**Issue by protobits** [ros/nodelet_core#25]
Hi,
the use of callbacks and threads in terms of servicing callbacks inside the nodelet ecosystem is not clearly documented and is confusing. It would be nice if more detail could be provided for the nodelet documentation on the wiki. 

In particular, it is not clear to me on what is the effect of mixing the MT and ST node handles when subscribing from different nodelets associated with a single nodelet manager. It is also not clear how are threads in the thread pool used to service callbacks in either case.

I would like to know how can I achieve that a callback for a specific subscription can be generated in parallel to other subscriptions of other callbacks in the same nodelet, while still servicing other callbacks inside this same nodelet serially, and also servicing callbacks from differents nodelets in parallel (which I think is the default behavior).

Note: I have asked the relevant question on ROS answers and got no response after a couple of months.

**Comment by dirk-thomas** [comment]
Please add references to your questions on ROS answers.

**Comment by protobits** [comment]
Here is the question: http://answers.ros.org/question/172685/how-are-threads-used-to-service-callbacks-in-nodelets/

**Comment by protobits** [comment]
Hi, I'm wondering if it would be possible for you to have a look at this ros question. It has now two months old, it has over 1000 views and still no answer. I'm guessing that the nodelet developers might be the best people to answer this. I'm having many difficulties understanding the implications of using the MT handle and the interaction between subscribers using the ST and MT.

**Comment by tfoote** [comment]
The documentation at http://wiki.ros.org/nodelet#Threading_Model states that if you use the single threaded node handle you will get guarenteed single threaded. If you use the multithreaded API you callbacks will join the shared pool. If you want more fine grain control you should manage your own threads and callback queues. Overview here: http://wiki.ros.org/roscpp/Overview/Callbacks%20and%20Spinning
