### ISSUE TITLE
nodelet tutorial instructs to use deprecated PLUGINLIB_DECLARE_CLASS

### ISSUE THREAD

**Issue by bricerebsamen** [ros/nodelet_core#28]
in http://wiki.ros.org/nodelet/Tutorials/Porting%20nodes%20to%20nodelets

**Comment by esteve** [comment]
Fixed in the latest revision of the wiki: http://wiki.ros.org/nodelet/Tutorials/Porting%20nodes%20to%20nodelets?action=diff&rev1=17&rev2=18

Thanks for noticing!
