### ISSUE TITLE
The wiki page has outdated bug tracker url

### ISSUE THREAD

**Issue by dirk-thomas** [ros/nodelet_core#29]
http://wiki.ros.org/nodelet_core

Bug / feature tracker points to: https://code.ros.org/trac/ros-pkg/query?component=common&status=assigned&status=new&status=reopened

**Comment by esteve** [comment]
I've updated the wiki page to use the `PackageHeader` macro and updated the `package.xml` file in each branch to point to the correct bugtracker.

**Comment by esteve** [comment]
How long does it take for the wiki to be updated? Do I have to release a new version of `nodelet_core` for it to have effect?

**Comment by dirk-thomas** [comment]
The `doc` job will index the repository every three days. Commonly the branch is registered in the distribution file, then you don't need a new release.

**Comment by esteve** [comment]
@dirk-thomas Thanks. I'm closing the ticket now.
