### ISSUE TITLE
dependency in package.xml missing

### ISSUE THREAD

**Issue by kalectro** [ros/nodelet_core#3]
nodelet_core/nodelet/CMakeLists.txt:34 asks for the package message_runtime, but nodelet_core/nodelet/package.xml only adds it as a run_depend.
Did not compile for me, adding the line 

```
 <build_depend>message_runtime</build_depend>
```

did the trick

**Comment by dirk-thomas** [comment]
The current code builds perfectly fine - that is also the version the Debian package is built from on the buildfarm. CATKIN_DEPENDS are not build dependencies but only exported for packages which depend on nodelet so message_runtime being a runtime dependency only is correct.

If it did not build for you it is likely for a different reason. You may ask a specific question about your setup with detailed information what you did and what failed on answers.ros.org.
