### ISSUE TITLE
nodelet fails to link uuid

### ISSUE THREAD

**Issue by tfoote** [ros/nodelet_core#4]
nodelet_core/nodelet fails to build due to not having libuuid linked. Tiny
 patch attached.

 Environment:  Archlinux x64

From: https://code.ros.org/trac/ros-pkg/ticket/5598

**Comment by tfoote** [comment]
Patch at: https://code.ros.org/trac/ros-pkg/attachment/ticket/5598/nodelet_uuid.patch

**Comment by dirk-thomas** [comment]
Also affects bond_cpp - also fixed there.
