### ISSUE TITLE
image Header seq field is 0 when run as a nodelet

### ISSUE THREAD

**Issue by bafonso** [ros/nodelet_core#42]
My function:

```
void ProcessCameraFrame::imageCb(const sensor_msgs::ImageConstPtr& image_msg,
        const sensor_msgs::CameraInfoConstPtr& info_msg)
{
```

Is called back fine, I subscribe to it fine and I even can get the timestamps properly. but I cannot see .seq increasing as it should. Rostopic does show it increasing, so my Ptr variables are losing it somewhere. This is critical in order for me to know if I'm losing frames or not from the camera.

**Comment by tfoote** [comment]
Duplicate #32
