### ISSUE TITLE
how to correctly unload a nodelet

### ISSUE THREAD

**Issue by taogashi** [ros/nodelet_core#43]
It seems to me the command line `nodelet unload name manager` doesn't take any effect.
The class I create does nothing but printing "running" on the screen.
After entering the command line, it just says:

```
Unloading nodelet /hello_node_helloer from manager nodelet_manager
```

But the screen is still scrolled with "RUNNING".

``` c++
class helloer: public nodelet::Nodelet
{
    public:
        helloer()
        {
            NODELET_INFO("hello nodelet");
        }
        ~helloer()
        {
            NODELET_INFO("bye nodelet");
        }
    private:
        virtual void onInit(void);
};

void helloer::onInit(void)
{
    ros::Rate loop(2);
    while(ros::ok()) {
        NODELET_INFO("RUNNING..");
        loop.sleep();
    }
}

PLUGINLIB_EXPORT_CLASS(helloer, nodelet::Nodelet);
```

The same thing happens when I want to unload driver_nodelet from velodyne_nodelet_manager which come from package [velodyne](https://github.com/ros-drivers/velodyne).

**Comment by mikaelarguedas** [comment]
@taogashi Sorry for the late reply. I assume you figured it out by now, but calling unload on nodelets **is** the correct way to unload a nodelet. The problem you are facing is that your nodelet initialization function never exits. This doesnt seem to be the case with the velodyne nodelet from looking at the code, so this is likely a different problem there.

Thanks for reporting this! However, we encourage you to ask questions on [ROS Answers](http://answers.ros.org/) in the future following our [support guidelines](http://wiki.ros.org/Support). This should allow you to get answers from the entire community in a timely manner. If you open a question from ROS answers with a reproducible example, please consider posting the link to the question here for future readers.
