### ISSUE TITLE
Release for Groovy

### ISSUE THREAD

**Issue by wjwwood** [ros/nodelet_core#6]
I backported a fix for `nodelet` where `pluginlib` was not being declared as a transitive dependency.

https://github.com/ros/nodelet_core/commit/53d0f6779cecacac6edea748fbf29012015ba3f0

There are some other fixes that need releasing too, should we release it for Groovy soon?

**Comment by dirk-thomas** [comment]
+1

**Comment by wjwwood** [comment]
I'll do it.

**Comment by wjwwood** [comment]
Done: https://github.com/ros/rosdistro/pull/1533
