### ISSUE TITLE
nodelets crash and repeatedly fail to respawn upon jumping system time

### ISSUE THREAD

**Issue by astaa-nrec** [ros/nodelet_core#8]
Launch the following launch file:

```
<launch>

    <node pkg="nodelet" type="nodelet" name="manager" args="manager">
      <param name="num_worker_threads" value="8" />
    </node>

    <node pkg="nodelet" type="nodelet" name="plus"
          args="load test_nodelet/Plus /manager" respawn="true"
          output="screen">
    </node>

</launch>
```

Now set the system time ahead to one minute in the future:

```
$ date
Tue Nov 12 15:35:04 EST 2013
$ sudo date --set="Tue Nov 12 15:36:04 EST 2013"
Tue Nov 12 15:36:04 EST 2013
```

You will observe the nodelet die repeatedly, first with a "bond broken" message, then with the error:

```
Service call failed: service [/manager/load_nodelet] responded with an error: boost::lock_error
```

and then subsequently with the error:

```
Cannot load nodelet /plus for one exists with that name already
```

The issue can be traced to lines 109-117 of loader.cpp:

```
    // If requested, create bond to sister process
    if (res.success && !req.bond_id.empty())
    {
      bond::Bond* bond = new bond::Bond(nh_.getNamespace() + "/bond", req.bond_id);
      bond_map_.insert(req.name, bond);
      bond->setCallbackQueue(&bond_callback_queue_);
      bond->setBrokenCallback(boost::bind(&Loader::unload, parent_, req.name));
      bond->start();
    }
```

After the first crash of the nodelet, `bond_map_` still has an entry for the key "/plus". In that case, `bond_map_.insert(req.name, bond)` leaves the existing entry unmodified and deletes `bond`. The `lock_error` comes from the uses of `bond` after it has been deleted.

The issue appears to go away if the map entry is cleared first, like this:

```
    // If requested, create bond to sister process
    if (res.success && !req.bond_id.empty())
    {
      bond::Bond* bond = new bond::Bond(nh_.getNamespace() + "/bond", req.bond_id);
      bond_map_.erase(req.name);
      bond_map_.insert(req.name, bond);
      bond->setCallbackQueue(&bond_callback_queue_);
      bond->setBrokenCallback(boost::bind(&Loader::unload, parent_, req.name));
      bond->start();
    }
```

**Comment by dirk-thomas** [comment]
Can you please verify that the patch provided in pull request #9 fixes the problem for you?

**Comment by astaa-nrec** [comment]
Yes, things seem to work properly after I apply that patch.

**Comment by dirk-thomas** [comment]
Thanks for confirming. Pull request merged.

**Comment by astaa-nrec** [comment]
Looks like the fix was only merged for hydro. Will groovy get the update as well?

**Comment by dirk-thomas** [comment]
Yes, I will cherry pick the commit for groovy before the next release.
